[Flutter] 12 - Unit Tests
guilhermeqmaia/cryptos_project pull request #11
Opened 2022-10-13 12:52 UTC by guilhermeqmaia

Link do Card [aqui](https://warren.atlassian.net/jira/software/c/projects/EV/boards/454?modal=detail&selectedIssue=EV-881&quickFilter=850)

- Realizado os testes unitários do App
- Maior cobertura dos testes de widgets
- 100% de cobertura do App

![image](https://user-images.githubusercontent.com/113136109/195601039-9b03fa17-b2d6-4130-9c94-5ce59f5fb819.png)

2022-10-13 13:54 UTC, julialuciani approved these changes

2022-10-13 13:54 UTC, julialuciani commented on lib/conversion/view/conversion_screen.dart
> +              id: 'idjsaodsa',
Colocar nomes que façam sentido pode ajudar os colegas a entender seu código

2022-10-13 16:10 UTC, carloscasanovad approved these changes

2022-10-14 12:45 UTC, CarlosTSIlva requested changes

2022-10-14 12:45 UTC, CarlosTSIlva commented on lib/shared/common_model/move_model.dart
poh mano vamos la tu ta gastando memoria a toa kkk 
tu pode usar assim :

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/97469958/195849802-32d2386a-2c34-41cb-9032-77a8c9b1ae80.png">

2022-10-14 12:45 UTC, CarlosTSIlva commented
ajusta ai e me chama dps

2022-10-14 13:34 UTC, CarlosTSIlva approved these changes

2022-10-14 13:34 UTC, closed without merging